### ISSUE TITLE
Minor problem regarding MSM config in ciftify_recon_all

### ISSUE THREAD

**Issue by ymstmshr** [edickie/ciftify#111]
Thanks for sharing the useful tool.
I'm trying to deploy the latest 2.3.2-2 for subject 007 (or sub-007) but I can't.

Downloaded from the web and installed manually by:
> pip install ciftify-2.3.2-2

For the subject 007, first I tried ciftify_recon_all by:
> ciftify_recon_all 007 --ciftify-work-dir "${ciftify_output_dir}" --fs-subjects-dir "${freesurfer_dir}"

and then I get error:

> Running version of MSM does not match config /home/dcn/ymm/anaconda3/lib/python3.7/site-packages/ciftify/data/hcp_config/MSMSulcStrainFinalconf

I'd appreciate if you could give some suggestion.
Thanks in advance.

**Comment by edickie** [comment]
Yes, the Multimodal Surface Matching (MSM) binary dependancy should be installed separately. An older version of this algorithms is available with FSL, so make sure that your $PATH is pointing to the correct one.

The binaries that should work are available for download at: https://github.com/ecr05/MSM_HOCR/releases

(or use the Docker version (https://hub.docker.com/r/tigrlab/fmriprep_ciftify/

**Comment by ymstmshr** [comment]
Thank you very much for your suggestion.
I forgot setting $PATH to the binary file (FSL's msm was used).

Now ciftify works so well.

**Comment by edickie** [comment]
thanks!
