### ISSUE TITLE
ciftify_statclust_report can't run with options served 

### ISSUE THREAD

**Issue by DearBraveJohn** [edickie/ciftify#115]
Dear Erin,
    I run the ciftify_statclust_report with some options but the context it gives to me is "Usage: ciftify_statclust_report [options] <func.dscalar.nii>", which my input is 
" ciftify_statclust_report --min-threshold * --max-threshold * --left-surface * --right-surface * --left-surface-area * --right-surface-area * --outputbase * <my map file(.dscalar.nii)>" (* denote the specific context put into).
  The command can run with no options served, but my situation must specify the surface and area options, could you look at it, deeply thanks!

**Comment by DearBraveJohn** [comment]
oops, the input of my command is wrong, sorry

**Comment by edickie** [comment]
Thanks for letting me know! What was the mistake? I'll make an issue to add
a more useful error message in the future.

**Comment by DearBraveJohn** [comment]
The mistake is made by myself 😂 I simply rerun the command without serving the '--outputbase' option which contains path previously, it  worked.

**Comment by DearBraveJohn** [comment]
Sorry to bother, by the way I think you should update ciftify documentation page's reference part https://edickie.github.io/ciftify/#/07_references with putting your ciftify NeuroImage article on top, so let people citing this useful tool easily, it really helps my work a lot, thanks!
