### ISSUE TITLE
ciftify_PINT_vertices command not found

### ISSUE THREAD

**Issue by renxili** [edickie/ciftify#135]
Hi all:

I was trying to run the PINT on one of our subject but my bash could not find the command "ciftify_PINT_vertices". I have checked other commands like "cifti_vis_PINT" and they works fine. I have checked the  /Users/renxili/opt/anaconda3/lib/python3.7/site-packages/bin and I can find ciftify_PINT_vertices.py and its executable file. Do you have any suggestions on what might go wrong? Many thanks!

**Comment by edickie** [comment]
sorry, I'm stumped.. cifti_vis_PINT and ciftify_PINT_vertices are installed
the same way so I have no idea why one would work and not the other..

**Comment by renxili** [comment]
That is exactly what I was thinking and confused about. It there any way we can re-install the ciftify package?

**Comment by renxili** [comment]
Okay, I re-installed ciftify and it now works. Thanks!

**Comment by renxili** [comment]
Hi: 
I have a follow-up problem for the PINT. I tried ciftify_PINT_vertices on one of the example subject but it always gives me an error of access the file while I have already set all folders and files to Read&Write in Finder. Would you mind take a look of what might go wrong?

(base) Renxis-Mac-mini:ciftify_demo_01 renxili$ ciftify_PINT_vertices --pcorr \${CIFTIFY_WORKDIR}/sub-50005/MNINonLinear/clean.dtseries.nii \${CIFTIFY_WORKDIR}/sub-50005/MNINonLinear/fsaverage_LR32k/sub-50005.L.midthickness.32k_fs_LR.surf.gii \${CIFTIFY_WORKDIR}/sub-50005/MNINonLinear/fsaverage_LR32k/sub-50005.R.midthickness.32k_fs_LR.surf.gii /Yeo7_2011_80verts.csv /sub-50005_task-rest
Traceback (most recent call last):
  File "/Users/renxili/opt/anaconda3/bin/ciftify_PINT_vertices", line 10, in <module>
    sys.exit(main())
  File "/Users/renxili/opt/anaconda3/lib/python3.7/site-packages/ciftify/bin/ciftify_PINT_vertices.py", line 517, in main
    fh = logging.FileHandler('{}_pint.log'.format(output_prefix))
  File "/Users/renxili/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/renxili/opt/anaconda3/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/sub-50005_task-rest_pint.log'
