### ISSUE TITLE
Does ciftify_recon_all only accept output from freesurfer?

### ISSUE THREAD

**Issue by renxili** [edickie/ciftify#136]
Hi:

Our team is using CONN tool box under Matlab to process the anatomical images, which gives an output in nifti format. Does ciftify_recon_all only accept output from freesurfer? Can we convert such CONN output to the cifti format?

Best,
Renxi

**Comment by edickie** [comment]
I haven't worked with CONN before - so I don't know exactly, but ciftify_recon_all does have a lot of "hard-coded" assumptions that the input data will follow the file naming conventions and resampling spaces of a freesurfer "recon_all" pipeline output. So I wouldn't expect it to work with another packages outputs.

**Comment by renxili** [comment]
Thank you!
