### ISSUE TITLE
T1w anatomical normalization issue

### ISSUE THREAD

**Issue by eburkevt** [edickie/ciftify#171]
Ciftify completes without error on the subjects I've tried so far, but I'm getting what looks to be bad Ciftify-based MNI normalizations for the fmriprep preprocessed T1w images.  I believe where MNI normalization occurs is in the "Registering T1wImage to MNI template using FSL FNIRT" step of **ciftify_recon_all**.

The output from a subject from our lab shows the issue (note the distortion along the top of the brain, particularly in the pre/post central regions)

![image](https://user-images.githubusercontent.com/5192968/193684038-7b62b44e-4fdd-4f0d-96a7-2dfd885fceb6.png)

Have anyone seen this before? Is there a way to prevent this or improve the normalization? 
Does the T1w normalization issue impact the analysis of the surface fMRI data produced by Ciftify?

Also, here is was I got for one the Ciftify example subjects (sub-50004 from the tutorial). This subject also shows some slight deformity in the pre/post central gyral regions, although not as extreme as in the above case.

![image](https://user-images.githubusercontent.com/5192968/193684568-d6a0c64f-d9e7-4cf3-a037-dde48535a4eb.png)

Here are my settings ...
System Info:
    OS: Linux
    Hostname: mica
    Release: 3.10.0-862.3.2.el7.x86_64
    Version: #1 SMP Mon May 21 23:36:36 UTC 2018
    Machine: x86_64
ciftify:
    Version: 2.3.3
wb_command:
    Path: /onrc/home/pipeline/data/pipelineb/home/Chyatt/onrc/data/Apps/workbench/bin_rh_linux64/wb_command
    Version: 1.5.0
    Commit Date: 2021-02-16 13:46:47 -0600
    Operating System: Linux
freesurfer:
    Path: /opt/freesurfer-6.0/bin
    Build Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
FSL:
    Path: /opt/fsl/fsl-6.0.3
    Version: 6.0.3:b862cdd5
---### End of Environment Settings ###---

Issue occurs with FSL v5.0.11 also.

**Comment by edickie** [comment]
Thanks for posting this. The good news is that the T1w normalization _shouldn't_ be to detrimental to the surface based fMRI. The same (bad) warp is used for both the functional and surfaces - so even though they look weird - they should still be aligned to each other. In this way, the quality of the T1w to functional registration is more important.

While I say that - the deformity after in the MNI warp in your participant does look particularly bad. This type of deformity is known to happen with FSL's FNIRT (which is what ciftify is using). I beleive it has something to do with the brain masking? Might be worth checking FSL supports on neurostars to see if there are any fixes?

**Comment by eburkevt** [comment]
> Thanks for posting this. The good news is that the T1w normalization _shouldn't_ be to detrimental to the surface based fMRI. The same (bad) warp is used for both the functional and surfaces - so even though they look weird - they should still be aligned to each other. In this way, the quality of the T1w to functional registration is more important.
> 
> While I say that - the deformity after in the MNI warp in your participant does look particularly bad. This type of deformity is known to happen with FSL's FNIRT (which is what ciftify is using). I beleive it has something to do with the brain masking? Might be worth checking FSL supports on neurostars to see if there are any fixes?

Thank you for your reply. I will look into what I can do regarding FNIRT based normalization.
