### ISSUE TITLE
ciftify_subject_fmri error

### ISSUE THREAD

**Issue by bamal** [edickie/ciftify#45]
I tried to convert Nifti a 4D volume to surface and  I got this error: 
```
ciftify_subject_fmri MYBASEDIR/fmri_s0025447_session3_rest.nii.gz 0025447 out
Subject HCPfolder does not exit
```
Any insights related to this please ?

**Comment by edickie** [comment]
Hey Amal,

Are you working from the current master or the latest release? I would
recommend the latest release...the master is in a little flux in prep for a
new release next week.

Sorry, I should have warned about that before,
Erin

**Comment by edickie** [comment]
Also, did you run ciftify_recon_all to generate the subject surface info
before running this step?

Thanks,
Erin
