### ISSUE TITLE
Issue running citify_subject_fmri with --FLIRT-to-T1w option

### ISSUE THREAD

**Issue by NeuroImagingWorld** [edickie/ciftify#64]
citify_subject_fmri with --FLIRT-to-T1w as below is giving usage error 

>> _ciftify_subject_fmri --hcp-data-dir ${HCP_DIR} --FLIRT-to-T1w func.nii.gz subjid mapname_

Error: _Usage:
  ciftify_subject_fmri [options] <func.nii.gz> <Subject> <NameOffMRI>_

Its running fine without --FLIRT-to-T1w option as below, 
>> _ciftify_subject_fmri --hcp-data-dir ${HCP_DIR}  func.nii.gz subjid mapname_

Can you please suggest if you see any issues

**Comment by edickie** [comment]
Just to check, are you running the newest version? If you run ciftify_subject_fmri --help do you see the --FLIRT-to-T1w flag.

I ask because it is a newer option. Although, before this flag was added --FLIRT-to-T1w was the default behaviour so it might be that it is working fine for you...

**Comment by NeuroImagingWorld** [comment]
Hi Erin, 

You are right, I don't see --FLIRT-to-T1w in help, I just installed latest version. Will keep you posted if we run into any issues.

     Uninstalling ciftify-1.0.1:
     Successfully uninstalled ciftify-1.0.1
     Successfully installed ciftify-2.0.2

Thanks

**Comment by NeuroImagingWorld** [comment]
Its working. Thanks
