### ISSUE TITLE
bug in 2.0.3

### ISSUE THREAD

**Issue by oricon** [edickie/ciftify#66]
I think there might be a bug in the latest update. I tried installed the update with pip but there was an error. (I replicated the problem on another computer with Python 3.6.5)

> Successfully built ciftify
> Installing collected packages: ciftify
> Exception:
> Traceback (most recent call last):
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
>     status = self.run(options, args)
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
>     use_user_site=options.use_user_site,
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
>     **kwargs
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
>     use_user_site=use_user_site, pycompile=pycompile,
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
>     warn_script_location=warn_script_location,
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/wheel.py", line 327, in move_wheel_files
>     console, gui = get_entrypoints(ep_file)
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/site-packages/pip/_internal/wheel.py", line 143, in get_entrypoints
>     console = dict(_split_ep(v) for v in console.values())
> ValueError: dictionary update sequence element #4 has length 3; 2 is required

So I did a manual install and still have an issue running commands:

> [joseph.orr@gfx bin$ ciftify_subject_fmri --SmoothingFWHM 2 --ciftify-work-dir $outdir --already-in-MNI $func $subject $label
> Fatal Python error: Py_Initialize: can't initialize sys standard streams
> Traceback (most recent call last):
>   File "/apps/psyc/ciftify/2.0.3/ciftify/io.py", line 9, in <module>
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/logging/__init__.py", line 26, in <module>
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/traceback.py", line 5, in <module>
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/linecache.py", line 11, in <module>
>   File "/apps/psyc/anaconda3/python35_520/lib/python3.6/tokenize.py", line 27, in <module>
> ImportError: cannot import name 'open'
> Aborted (core dumped)

**Comment by edickie** [comment]
Thanks for lettinge know. Will debug today.

**Comment by edickie** [comment]
We think we fixed everything with the 2.0.4-alpha version.

**Comment by oricon** [comment]
Hi the install works without a problem, but now I run into an error with niio in ciftify_subject_fmri when it gets to the Subcortical Processing:

Traceback (most recent call last):
  File "/apps/psyc/ciftify/2.0.4/ciftify/bin/ciftify_subject_fmri", line 1062, in <module>
    main()
  File "/apps/psyc/ciftify/2.0.4/ciftify/bin/ciftify_subject_fmri", line 1057, in main
    ret = run_ciftify_subject_fmri(settings, tmpdir)
  File "/apps/psyc/ciftify/2.0.4/ciftify/bin/ciftify_subject_fmri", line 190, in run_ciftify_subject_fmri
    tmpdir)
  File "/apps/psyc/ciftify/2.0.4/ciftify/bin/ciftify_subject_fmri", line 893, in subcortical_atlas
    func_vx_size = ciftify.niio.voxel_spacing(input_fMRI)
AttributeError: module 'ciftify' has no attribute 'niio'

Here's the last line of the ciftify_subject_fmri.log:
-------------------------------------------------------------
2018-06-23 15:53:57.789319 : Subcortical Processing
-------------------------------------------------------------

VolumefMRI: /fdata/scratch/joseph.orr/adaptcog/fmri/hcp/sub-M80301092/MNINonLinear/Results/task-ritl_acq-MB_run-01/task-ritl_acq-MB_run-01.nii.gz

**Comment by edickie** [comment]
oops sorry. It looks like the final bug fixes were not included in the
2.0.4 release. 2.0.5 has been pushed.

**Comment by oricon** [comment]
Looks like this bug is fixed, thanks!
