### ISSUE TITLE
How to run "ciftify usage example" in a docker

### ISSUE THREAD

**Issue by romainviard** [edickie/ciftify#81]
First of all, thank a lot to share your work.
I wish to run ciftify in a docker so I cloned from github the project ciftify, build the Dockerfile and ran it....  
But I do not understand how that can work ....because It seems to me that the dockerfile open only a jupyter notebook and thats it ...
I think I have missed something....
Could you please say a word on that ?

**Comment by romainviard** [comment]
And if I may could you specify which version of msm should be run with ciftify ? 
because I tried MSM_HOCR_v1,MSM_HOCR_v2, the one in fsl 5.0.11 (msm command) ...I didn't try yet the compiled from github project (https://github.com/ecr05/MSM_HOCR)...
Each one give me the same error message " Running version of MSM does not match config /home/global/anaconda3/lib/python3.5/site-packages/ciftify/data/hcp_config/MSMSulcStrainFinalconf"

Do you have an idea about this bug ?
Thanks very much in advances,
RV

**Comment by edickie** [comment]
Thanks for your interest! You highlight the fact that I need to update the documentation very soon to reflect some upgrades/changes that were implemented in the last two weeks. 

A major addition is that this project now contains two Docker files 

1. A large docker that runs the pipelines (ciftify_recon_all and ciftify_subject_fmri + QC along side fmriprep). (This one is built as a BIDS app and runs alongside fmriprep, size >12G). (location: ciftify/bidsapp/Docker, it is also hosted on dockerhub at https://hub.docker.com/r/tigrlab/fmriprep_ciftify/) 
2. A small docker with only the python environment and connectome-workbench. This one is a lighter programming environment for working with CIFTI files after they been generated. It's also now available on Binder for tutorials. This one is in the base folder.

Some more details on these use cases are in this poster https://docs.google.com/presentation/d/1QFrfzw7JMfHzDhuuOgATdrlYcBWK12sMaLcMGghTJ-s/edit?usp=sharing. More instructrions from running the container are in this repo https://github.com/edickie/bids-on-scinet. The examples in the repo work from singularity image built from the dockerhub image.

To answer your second question. No, the version of MSM in FSL is not the one currently packaged with FSL. There's some odd politics going on there. And Matt Glasser is strongly insisting on the github one. You can download the complied binary's directly from the releases section of their github though (https://github.com/ecr05/MSM_HOCR/releases).  (or just use tigrlab/fmriprep_cifitify)

**Comment by romainviard** [comment]
All right, it is so much clearer now. It's so kind to reply, thanks a lot.
Good Luck
