### ISSUE TITLE
log error typo thingy ciftify_clean_img

### ISSUE THREAD

**Issue by colinhawco** [edickie/ciftify#86]
In ciftify_clean_img

   logger.error('Indicated colBIDS_ZHH/sub-10186/ses-02/func/sub-10186_ses-02_task-rest_bold.nii.gzumn {} not in confounds'.format(colname_arg))

Don't imaging all that ZHH bit is supposed to be coded in there : )

**Comment by edickie** [comment]
fixed in version 2.1.0
