### ISSUE TITLE
MSMsulc files not found within singularity image

### ISSUE THREAD

**Issue by ljhearne** [edickie/ciftify#94]
I have built a singularity image using docker which is functioning correctly. However it doesn't find the appropriate MSM files.

Here is the error:
`Cannot find 'msm' binary. Please download and install MSM from https://github.com/ecr05/MSM_HOCR_macOSX, or run with the "--surf_reg FS" option`

Critically, when using the `--surf_reg FS flag` it works fine.

Do I need to install the MSM binaries and mount them to the singularity image?

Here is my code:
```
module purge
module load singularity
subject='10189'

#bids_input='/scratch/qm89/data/prepro/'
export freesufer_license='/projects/qm89/license.txt'
export FS_LICENSE='/projects/qm89/license.txt'
export ciftify_container='/scratch/qm89/Containers/tigrlab_fmriprep_ciftify.simg'

## build the mounts
singdir='/mnt/'
bidsdir=${singdir}data/rawdata
outdir=${singdir}data/prepro
workdir=${singdir}scratch/

singularity run --cleanenv --bind /scratch/qm89:/mnt \
  ${ciftify_container} \
      ${bidsdir} ${outdir} participant \
      --participant_label=${subject} \
      --fmriprep-workdir ${workdir} \
      --n_cpus 8 \
      --fs-license /mnt/license.txt \
    --task_label='rest' \
    --v

**Comment by edickie** [comment]
No, your right. The msm binary should be in the docker image. I'll
troubleshoot tomorrow and see if I can replicate the problem on my end.

Thanks for letting me know,
Erin

**Comment by edickie** [comment]
new image just pushed to dockerhub! version 1.1.8-2.1.1 

(note: this one also has an updated fmriprep version (1.1.8) and python dependencies) let me know if that is an issue.
